const store =[
    {nombre:"Equipo Intel Core I3 10100f Pro Gamer_SSD_GTX1650 4Gb",descripcion: "Gabinete StarkGear Spider RGB - lateral en cristal templado. Fuente Cougar / DeepCool 500w 80 Plus.    Mother Asrock h510 - con usb 3.0, soporte DDR4 hasta 64Gb.    Procesador Intel I3 10100f 4 núcleos 8 hilos 3,6Ghz 4,3Ghz.    Memoria Kingston 8Gb DDR4 2666mhz. Disco SSD Kingston A400 480Gb. Gráficos Geforce GTX1650 4Gb", precio: "650", id: "1", img: "/imagenes/basic-removebg-preview (1).png", idcat:"pc"},
    {nombre:"Equipo Intel Core I5 12400F Full Gamer_16Gb_SSD_RTX3060 12Gb",descripcion: "Gabinete DeepCool Matrexx 50 ADD-RGB -Cristal templado - 4 fanes. Fuente Cougar / DeepCool 600w 80 Plus. Mother Asus / Gigabyte B660.  Procesador Intel Core I5 12400F 6 núcleos 12 hilos hasta 4,4Ghz. Memoria Kingston 16Gb DDR4 3200mhz (2 x 8Gb). Disco SSD PCIe Kingston NV2 500Gb. Gráficos Geforce RTX3060 12 Gb", precio: "1275", id: "2", img: "/imagenes/descarga__2_-removebg-preview.png", idcat:"pc"},
    {nombre:"Equipo Intel Core I7 10700f Full Gamer_16Gb_SSD PCIe_RTX3060 12Gb",descripcion: "Gabinete DeepCool Matrexx 50 ADD-RGB -Cristal templado - 4 fanes. Fuente Cougar / DeepCool 600w 80 Plus. Mother Gigabyte B560M Gaming HD. Procesador Intel Core I7 10700f 8 núcleos 16 hilos 2,9 / 4,8Ghz con Cooler Master Hyper 212 Spectrum. Memoria Kingston 16Gb DDR4 2666mhz (2 x 8Gb). Disco SSD PCIe Kingston NV2 500Gb.   Gráficos Geforce RTX3060 12Gb", precio: "1325", id: "3", img: "/imagenes/images__1_-removebg-preview.png", idcat:"pc"},
    {nombre:"Equipo Intel Core I9 12900Kf Full Gamer_32Gb + SSD PCIe 1Tb + RTX4080",descripcion: "Gabinete Cooler Master HAF500 negro o blanco a elección con fanes ARGB. Fuente Cooler Master MWE 850w 80 Plus Gold. Mother Asus Z790-P soporte m.2 _ 4 bancos DDR5 _ PCIe 5.0 _ USB 3.2 _ USB C. Procesador Intel Core I9 12900KF 16 núcleos 24 hilos hasta 5,2Ghz. Watercooling EVGA Liquid RGB water cooling 280. Memoria 32Gb DDR5 5200mhz (2 x 16). Disco SSD PCIe Kingston NV2 1Tb. Gráficos Geforce RTX4080", precio: "4150", id: "4", img: "/imagenes/descarga__1_-removebg-preview.png", idcat:"pc"},
    {nombre:"Equipo AMD Ryzen 3 4100 Pro Gamer con Radeon RX6500 4Gb",descripcion: "Gabinete StarkGear Spider RGB - lateral en cristal templado. Fuente Cougar / DeepCool 500w 80 Plus. Mother Asus A320 - Sata III - USB 3.0. Procesador AMD Ryzen 3 4100 4 núcleos 8 hilos 3.8GHz / 4.0GHz. Memoria 8Gb DDR4 3200mhz. Disco SSD Kingston A400 480Gb. Gráficos Radeon RX6500 4Gb", precio: "650", id: "5", img: "/imagenes/descarga-removebg-preview (1).png", idcat:"pc"},
    {nombre:"Equipo AMD Ryzen 5 5600X Full Gamer _ 16gb _ SSD _ RTX3060",descripcion: "Gabinete Perseo CN21 _ Cristal templado _ incluye 3 fanes RGB. Fuente Cougar / DeepCool 600w 80 Plus. Mother Asus Prime B550M-A AC _ Soporte SSD PCIe _ Sata III _ USB 3.0. Procesador AMD Ryzen 5 5600X 3,7 / 4,6Ghz 6 núcleos _ 12 hilos. Memoria Kingston 16Gb DDR4 3200mhz (2 x 8Gb). Disco SSD Kingston A400 480Gb. Gráficos Geforce RTX3060 12Gb", precio: "1250", id: "6", img: "/imagenes/images__2_-removebg-preview.png", idcat:"pc"},
    {nombre:"Memoria Kingston Fury Beast 16GB DDR4 3600Mhz", descripcion:"Kingston FURY ™ Beast DDR4 proporciona un poderoso aumento de rendimiento para juegos, edición de video y renderizado con velocidades de hasta 3733MHz . Esta actualización rentable está disponible en velocidades de 2666 MHz a 3733 MHz, latencias CL15 a 19, capacidades de módulo único de 4 GB a 32 GB y capacidades de kit de 8 GB a 128 GB. Cuenta con overclocking automático Plug N Play a 2666MHz y está preparado para Intel XMP y listo para AMD Ryzen ™. FURY Beast DDR4 se mantiene fresco con su elegante disipador de calor de bajo perfil. ", precio:"69", id:"7", img:"/imagenes/ddr4-removebg-preview.png", idcat:"componentes"},
    {nombre:"Memoria Kingston Fury Beast RGB 16gb DDR5 5600Mhz White Edition", descripcion:"Kingston FURY™ Beast DDR5 RGB1 te permite hacer overclocking con estilo en plataformas para videojuegos de última generación mediante tecnología punta. Sé testigo de la velocidad mejorada del DDR5 con el doble de bancos de memoria y el doble de tamaño de ráfaga. El increíble sistema personalizable de iluminación RGB con el software de Kingston FURY CTRL™ y la tecnología Infrared Sync Technology™ con el añadido del disipador térmico de nuevo diseño en blanco o negro, que te diferenciarán del resto, dentro y fuera de los juegos.", precio:"100", id:"8", img:"/imagenes/ddr5-removebg-preview.png", idcat:"componentes"},
    {nombre:"CPU Intel Core i3 12100 Alder Lake 1700", descripcion:"Cantidad de núcleos 4    # of Performance-cores 4    # of Efficient-cores 0    Cantidad de subprocesos 8    Frecuencia turbo máxima 4,30 GHz    Performance-core Max Turbo Frequency 4.30 GHz    Performance-core Base Frequency 3.30 GHz    Gráficos del procesador ‡ Gráficos UHD Intel® 730    Frecuencia de base de gráficos 300 MHz    Frecuencia dinámica máxima de gráficos 1.40 GHz    Caché 12 MB Intel® Smart Cache    Total L2 Cache 5 MB  Processor Base Power 58 W    Maximum Turbo Power 89 W", precio:"209", id:"9", img:"/imagenes/i3.png", idcat:"componentes"},
    {nombre:"CPU Intel Core i7 11700 Rocket Lake 1200", descripcion:"Cantidad de núcleos 8    Cantidad de subprocesos 16    Frecuencia básica del procesador 2,50 GHz    Frecuencia turbo máxima 4,90 GHz    Caché16 MB Intel® Smart Cache    Velocidad del bus 8 GT/s    TDP65 W", precio:"515", id:"10", img:"/imagenes/i7-removebg-preview.png", idcat:"componentes"},
    {nombre:"ZOTAC GeForce GT1030 2gb gddr5", descripcion:"Core Clock 1227 / 1468 MHz    Memory Clock 6.0 GHz    Memory Size 2048 MB    Memory Type DDR5    Memory Bus 64 bit", precio:"138", id:"11", img:"/imagenes/gt1030-removebg-preview.png", idcat:"componentes"},
    {nombre:"GPU Gigabyte GeForce RTX3050 Eagle OC 8Gb", descripcion:"Multiprocesadores NVIDIA Ampere Streaming    Núcleos RT de 2.ª generación Núcleos    Tensor de 3.ª generación Con la    tecnología de GeForce RTX™ 3050    Integrada con interfaz de memoria de 128 bits GDDR6 de 8 GB    Sistema de refrigeración WINDFORCE 2X con ventiladores giratorios alternativos Ventiladores    de hoja exclusivos de 90 mm    Placa posterior de protección    RELOJ DE NÚCLEO      1777 MHz", precio:"474", id:"12", img:"/imagenes/gt3050-removebg-preview.png", idcat:"componentes"},
    {nombre:"GPU Gigabyte GeForce RTX 4090 Gaming OC 24Gb", descripcion:"Multiprocesadores de transmisión NVIDIA Ada Lovelace:    hasta el doble de rendimiento y eficiencia energética    Núcleos tensoriales de 4.ª generación: hasta 4 veces más rendimiento con DLSS 3 que con renderizado de fuerza bruta    Núcleos RT de tercera generación: rendimiento de trazado de rayos de hasta 2X    Desarrollado por GeForce RTX® 4090    Integrado con interfaz de memoria de 24 GB GDDR6X de 384 bits    Sistema de refrigeración WINDFORCE    Fusión RGB  BIOS doble    Placa trasera de metal de protección    Soporte anti-hundimiento", precio:"2675", id:"13", img:"/imagenes/rxt4090.png", idcat:"componentes"},
    {nombre:" GPU Biostar Radeon RX6500XT 4Gb GDDR6", descripcion:" GPU	Radeon RX6500XT    PRODUCT CERTIFICATION	DirectX 12    PRODUCT FEATURES	Display port  PCI-E 4.0    ENGINE CLOCK 2310/2610/2815MHz    MEMORY CLOCK	18.0Gbps    MEMORY SIZE	4GB    MEMORY TYPE	DDR6", precio:"300", id:"14", img:"/imagenes/gpu6500-removebg-preview.png", idcat:"componentes"},
    {nombre:"GPU Gigabyte Radeon RX7900XT Gaming OC 20Gb", descripcion:"Desarrollado por Radeon™ RX 7900 XT    Integrado con interfaz de memoria de 20 GB GDDR6 de 320 bits    Sistema de refrigeración WINDFORCE    Fusión RGB    BIOS doble    Placa trasera de metal de protección    Soporte anti-hundimiento      RELOJ DE NÚCLEO        Boost Clock* : hasta 2535 MHz (Tarjeta de referencia: 2400 MHz)    Game Clock* : hasta 2175 MHz (Tarjeta de referencia: 2000 MHz)", precio:"1545", id:"15", img:"/imagenes/gpu7900-removebg-preview.png", idcat:"componentes"},
    {nombre:"Mouse MSI Clutch Gm10 Ergonómico 4 botones hasta 2400dpi", descripcion:"USB 2.0 INTERFACE: USB    DPI SWITCH: 800 / 1000(default) / 1600 / 2400    COLOR: Black    WEIGHT(G): 104gb    LED LIGHT: Red Dragon LED / Wheel (four colors)    RESPONSE TIME: 1ms    MAIN KEY SWITCHES: 10 Million+ clicks    LIGHTING EFFECTS: Logo LED: Breathing effect -     Wheel LED: by DPI (800 Blue / 1000 Red / 1600 Green / 2400 Purple)    USB CABLE: 1.8m    SENSOR: PixArt ADSN-5712    DIMENSIONS(MM): 125 (L)*64 (W)*43 (H) mm    BUTTONS: 4    OS SUPPORTED: Windows 10/ 8.1/ 8/ 7/ Vista/ XP", precio:"13", id:"16", img:"/imagenes/m16-removebg-preview.png", idcat:"Perifericos"},
    {nombre:"Mouse Logitech G502 Lightspeed Wireless", descripcion:"El mouse G502 es todo un icono que ha ocupado las primeras posiciones de las listas generación tras generación. Y es el mouse que eligen quienes juegan en serio. Ahora, el mouse G502 se une a las filas de los mouse inalámbricos para juegos más avanzados del mundo con el lanzamiento de G502 LIGHTSPEED. LIGHTSPEED es una tecnología ultrarrápida y confiable con desempeño probado en competencia por profesionales de eSports. G502 LIGHTSPEED posee además el sensor de próxima generación HERO 16K y es compatible con POWERPLAY. Junto con esta novedosa tecnología avanzada, G502 LIGHTSPEED mantiene esa forma apreciada por todos y logra una reducción de peso de 7 gramos.", precio:"110", id:"17", img:"/imagenes/images-removebg-preview.png", idcat:"Perifericos"},
    {nombre:"Razer Cynosa Lite + Razer Abyssus Lite - Chroma Bundle", descripcion:"TECLADO RAZER CYNOSA LITE    - Teclas de membrana de nivel para juegos    Iluminación Chroma de una sola zona    Teclas programables con grabación de macros al-vuelo    Modo Juego dedicado    Matriz de teclas optimizada    Compatible con Razer Synapse    Distribución de teclas en Español    Medidas: 457 x 174 x 33 mm    Peso: 904 grs.    MOUSE RAZER ABYSSUS LITE    Diseño ergonómico ambidiestro    Sensor óptico de 6400 DPI reales    Iluminación Chroma de una sola zona    1000 Hz Ultrapolling    Cable de 2 metros    Compatible con Razer Synapse    Medidas: 115 x 63 x 37 mm    Peso: sin cable 74 grs.", precio:"60", id:"18", img:"/imagenes/c60-removebg-preview.png", idcat:"Perifericos"},
    {nombre:"Logitech MK345 Comfort wireless combo", descripcion:"El kit cuenta con un Nano-receptor para los dos dispositivos    El teclado cuenta con reposamanos y altura ajustable del teclado que le brindan mayor comodidad.    Diseño resistente a derrames    Cómodo mouse de superficie texturada", precio:"37", id:"19", img:"/imagenes/c37.png", idcat:"Perifericos"},
    {nombre:"Teclado Logitech G213", descripcion:"Cada tecla de G213 está optimizada para mejorar la experiencia táctil y ofrecer una respuesta superrápida, hasta 4 veces superior a la de los teclados estándar. La matriz de prevención de efecto fantasma para juegos está programada para dominar el control al pulsar simultáneamente varias teclas de juego.    Añade un toque personal con cinco zonas de iluminación individuales con un espectro de hasta 16,8 millones de colores. Cambia colores según una configuración o un juego específico o simplemente para usar tus favoritos. El bajo índice de fuga luminosa alrededor de las teclas significa que pasa más luz por las letras, con lo que cada tecla es más brillante y más fácil de encontrar.* ", precio:"65", id:"20", img:"/imagenes/t64.png", idcat:"Perifericos"},
    {nombre:"Teclado mecánico Cooler Master SK653 WH Low Profile Bluetooth - Cherry Red - US", descripcion:"El teclado inalámbrico híbrido para juegos SK653 adopta un enfoque moderno del teclado mecánico clásico con interruptores de bajo perfil alojados en un chasis elegante.    INTERRUPTORES DE PERFIL BAJO        Una distancia de recorrido y un punto de actuación reducidos con la misma durabilidad y precisión características.    MEJORAS ERGONÓMICAS    Las teclas ergonómicas nuevas y mejoradas en comparación con su predecesor y los pies ajustables ahora le brindan una experiencia de escritura aún más cómoda.    DISEÑO DE ALUMINIO CEPILLADO.    Placa superior delgada, teclas flotantes y diseño minimalista creado pensando en la funcionalidad.      COMPATIBILIDAD CON VARIOS SISTEMAS OPERATIVOS       Compatible con Windows 8 y superior, macOS, iOS y Android: cambie fácilmente entre todos los dispositivos con una simple combinación de teclas.     CONTROL HÍBRIDO INALÁMBRICO        Elija entre conectividad por cable tipo C o inalámbrica Bluetooth 4.0 para hasta 3 dispositivos.", precio:"199", id:"21", img:"/imagenes/t200-removebg-preview.png", idcat:"Perifericos"}
];
export const getstore = () => {
    return new Promise ((resolve)=> {
        setTimeout (() => {
            resolve(store)
        },2000)
    })
}

export const getUnproducto = (id) => {
    return new Promise ((resolve)=>{
        setTimeout(()=>{
            const producto = store.find(prod => prod.id.toString() === id.toString())
            resolve(producto)
        }, 2000)
    })
}
export const getcategoria = (idcat) => {
    return new Promise ((resolve) => {
        setTimeout(()=>{
        const productosxcategoria = store.filter(prod => prod.idcat === idcat)
        resolve(productosxcategoria)
        }, 2000)
    })
}